### ISSUE TITLE
crash with files larger than 15MB

### ISSUE THREAD

**Issue by parabola19** [bytecode77/pe-union#11]
why? tried many times, binder closes after a LONG build loading (file 22mb + 1mb)

**Comment by bytecode77** [comment]
PEunion 3.x is currently on hold while PEunion 4.0 is under active development. The current version has a few issues, particularly it's detected by AV and is lacking important in-memory features.

Because I only have about 2-5 hours per week to work on my projects, I'm pushing for the new release, while leaving the current version as-is. I hope you understand that I won't fix the current version in order to release the new version in a timely manner.
