### ISSUE TITLE
Great Tool and Suggestions for 4.0

### ISSUE THREAD

**Issue by Odsodium** [bytecode77/pe-union#12]
This isn't an issue but I'm just telling you this tool is very good and I appreciate you will continue to update it after 4 years. However I have a suggestion to the new version which you are working on. It would be great to see that you could change the dropping location to a custom one eg. in the system folder. This is because the preset ones are very bad for tech savvy users, they could open task manager and find the file location. Also the UI design is very nice compared to other Binders and Crypters.
Great Job and best of luck to you

**Comment by bytecode77** [comment]
I have added it to the ToDo list. It's a small task and I generally implement what users require on a frequent basis. Thanks for your feedback! You're also welcome to suggest other drop locations that you think would be nice to have.

**Comment by Odsodium** [comment]
Thanks for your reply, I think it would be nice to have the user choose the drop location and maybe have a few presets (eg. temp, appdata, program data, program files). This way there is lots of flexibility with using the tool. Another thing that I think could be improved is the "melt" function, in my testing and experience it doesn't delete the file right away and it allows the user to open it twice or three times before deleting. I hope you find these suggestions helpful :)

**Comment by bytecode77** [comment]
Melt is on the ToDo list for the new version as the new version should have _at least_ the features that the current has. When I was creating the feature list, I already took note that melting wasn't implemented that well, but there's a lot of approaches that can be used to self-destruct.

I will also include more drop locations, not just a few, and the ability to choose an existing subfolder within that location.

Thanks for the suggestions ;)

**Comment by bytecode77** [comment]
# PEunion 4.0.0

The new version of PEunion has been released. All currently open GitHub issues were addressed in the release. Additionally, the new version is a complete rewrite and addresses known issues by fundamental architectural changes.

For more info, please read the main page of PEunion to get an overview over features & functionality.

*This message was posted in all currently open GitHub issues.*

It there are any issues in the new version, I would like to ask everybody to create a new GitHub issue instead of posting here. This way, I will have a better overview over issues in PEunion 3.x vs 4.0
