### ISSUE TITLE
Detected by Windows Defender

### ISSUE THREAD

**Issue by Odsodium** [bytecode77/pe-union#15]
No matter what I try to do, the file is detected by windows defender as "Trojan:Win32/Wacatac.B!ml" in version 4.0

**Comment by wizar-d** [comment]
fatass

**Comment by Odsodium** [comment]
> fatass

k

**Comment by bytecode77** [comment]
*(OT comments deleted)*

Does it happen with the .NET stub, or just the native stub? From my experience, the .NET stub was interestingly a lot less troublesome when evading detection. As funny as it sounds, encrypting strings has reduced detection the most. Apparently AV vendors do not have sufficient methods to statically analyze .NET binaries.

I also remember about 10 year ago you could just recompile a C# project and it was no longer detected, because back then, AV detected .NET binaries by signature and/or hash only.

I know for a fact that the native stub has been flagged by the same generic detection from multiple vendors a week prior to release. *(Maybe one of the testers had an AV installed, even though I've instructed them not to?)* I've pushed the 4.0 release anyway to get rid of the problems that PEunion 3.x had.

Even though the readme states that I won't release updates to fix detection issues, I still **do** work on evading heuristic flags (what Defender flagged) and HIPS related detection issues. However, to make it clear, since PEunion is public and has probably been uploaded to VT a hundred times, it will probably always be detectable.

That's the reason behind the two-layer architecture: To make it **easy** to change the stub in such a way that it is no longer detectable without changing anything in the second stage.

**Comment by Odsodium** [comment]
The issue occurs with the 32bit .NET stub (Using the Invoke method), with melt enabled and padding on >2. While testing I've noticed that changing the padding doesn't evade the anti-virus detection, however it changes the detection type (for windows defender). I think it would be highly unlikely that since PEunion's 4.0 release it would have been uploaded to VT more than 2-10 times as I tested it around 9-10 hours after you released it. But maybe this could be a reason? 

With the testers, did you instruct them to turn off sample submission in av's, in windows defender there is an option to turn off "Automatic Sample Submission". I scanned my payload on a site which doesn't distribute the samples (antiscan.me), but I got a few detections, then I tried testing it on a VM with windows defender and it detected it. If it released as FUD, I wouldn't think it would get detected in a few hours.

**Comment by bytecode77** [comment]
> changing the padding doesn't evade the anti-virus detection, however it changes the detection type

That's why padding is a must-have feature, because otherwise packer detection is guaranteed.

> it would be highly unlikely that [...] it would have been uploaded to VT more than 2-10 times as I tested it around 9-10 hours after you released it. But maybe this could be a reason? [...] did you instruct them to turn off sample submission in av's [...]?

I've sent screenshot on how to configure Windows Defender. And I'm using antiscan.me, too, becasue I upload the binaries hundreds of times in the process. But regardless of how exactly the binaries "leaked" to AV vendors, one way or another PEunion binaries will get heavily uploaded to VT in the next months and the detection will go up quickly. I've seen this with PEunion 3.x back in 2017.

My reason to rewrite PEunion is simple. PEunion 3.x lacked some very important features; It did not have RunPE implemented, but only the Drop feature, etc. I must have been very busy and/or ignorant back then, that's why I've decided to write a completely new version that supports all of this.

It took about half a year to write PEunion 4.0, in part because I have a busy life and I don't spend the majority of my time in front of my computer. This is also a reason why I don't sell crypter services: It's essentially a full-time job to maintain a crypter FUD.

Since I anticipated reports on PEunion not being FUD sooner or later, I've constructed the stub in such a way that the amount of code in the stub that someone has to change in order to make it FUD is reduced to the stub itself. That's about ~100 lines of assembly code. From the second stage forward, it is my job as the project maintainer to provider proper evasion techniques.

Right now, I'm really trying to help - but at the same time I know that when I fix detection issues today, a few days to weeks from now there will be YARA rules for the updated stub. It happened to r77, where I've spent 3 weeks on AV evasion and it got detected only a few days later.

That's the whole purpose behind the headline "FUD" on the main page. It's to let everyone know the difference between a crypter that's not FUD and a crypter that's just badly designed. PEunion is designed particularly to make adjustments that lead to FUD as easy as possible.

So to "get out" of the loop where I fix detection issues on demand that only last a few days, I suggest everyone to make the adjustments at the stub and to **not share** the stub with anyone else, including VirusTotal. I also strongly encourage to use antiscan.me or a similar service. This is the only viable option besides purchasing a crypter service to have a crypter that is actually FUD.

**Comment by Odsodium** [comment]
Thanks for your insightful comments, I will try modifying the stub myself and see where I get with that. Best of luck with you and your future programs

**Comment by Mich-ele** [comment]
Can you send me the screenshot on how to configure in order to evade Windows Defender?
I'm using .NET framework 32bit too.

**Comment by Odsodium** [comment]
> Can you send me the screenshot on how to configure in order to evade Windows Defender?
> I'm using .NET framework 32bit too.

I think that's for the user to play around and test with, that's why it's open source

**Comment by bytecode77** [comment]
> Can you send me the screenshot on how to configure in order to evade Windows Defender?

Did you read this thread, in particular my second post? I think you are looking for a quick fix or shortcut to get a crypter that's both free **and** FUD.

To put it short: This project is open source and public. To make it FUD and maintain it FUD long term, it requires several hours of work per day, which I will just not invest.

As for the solution: You can either decide to pay a crypter service from someone else. They typically spend **a lot** of time in maintaining it to be FUD, because it's their full-time **job**. Alternatively, the architecture of the stub is such that any experienced developer can make the proper changes to make this public release a "private" one for yourself.
