### ISSUE TITLE
video hướng dẫn

### ISSUE THREAD

**Issue by buivannhat1** [bytecode77/pe-union#16]
hi vọng bạn ra video hướng dẫn sử dụng cho tool này, và cho hỏi là nó có vượt qua" windows defender? "

**Comment by bytecode77** [comment]
Please post your questions in English language in the future. While I can use Google Translator, it makes the conversation hardly readable to anybody else.

There are no video tutorials. Most settings have a help-icon that you can click on to get more information. Otherwise, if you know what a crypter is and how to use one, the rest should be self explanatory.

Regarding AV evasion: I have already mentioned on the main page that I will not put in the work to maintain this crypter FUD. It would require several hours of work each day. Please read the section "FUD" on the main page to learn more about the reasons.
