### ISSUE TITLE
modifying stub

### ISSUE THREAD

**Issue by Elon-Sarif** [bytecode77/pe-union#20]
**first of all i'd love to thank you for the immense work u've made :)**

 so u've said that only the stub needed modification to be FUD. but i dont know where to look at in the code lmao.

when i open the pe-union.sln file in VS, could u give me some indication as where to look at ? (peunion, pebuild or pe compiler  folder?

 im relatively new to this game, sorry if it seems to be a dumb question.

also if u have some tips to make it FUD  i'd love to hear from a pro.

thanks for everything

**Comment by bytecode77** [comment]
> when i open the pe-union.sln file in VS, could u give me some indication as where to look at ? (peunion, pebuild or pe compiler folder?

Under `SlnBin/Stub` you have both stubs.

> im relatively new to this game, sorry if it seems to be a dumb question.
> 
> also if u have some tips to make it FUD i'd love to hear from a pro.

You really need to have the skills in order to pull something like this off. If you previously were just a user of crypters, then writing one or FUDding an existing will be a very difficult task. It always takes time to get there...

**Comment by Elon-Sarif** [comment]
i thought that maybe by adding some junk code it would do the trick lmao.

do u maybe have some tips of what should i start learning in order to make this stub fud again?

**Comment by bytecode77** [comment]
In the beta, the amount of junk code was acutally configurable - until I have discovered that it increases the detection rate. So, I have removed that option to not lead users into worsening their detection score. Now the amount of junk code is constant.

> do u maybe have some tips of what should i start learning in order to make this stub fud again?

You have two options: If you want to write a crypter or FUD an existing one, you have to start from zero and figure out what works best by reading + trial and error. That's the only way, since there is nobody or forum that will teach for free how to become a good reverse engineer or hacker.

If that's not your passion at all and you're looking for an efficient solution, then there's crypters that cost money. They cost money because it's a rather time consuming job to develop such software, as I have mentioned in [FUD.md](https://github.com/bytecode77/pe-union/blob/master/FUD.md).

**Comment by Elon-Sarif** [comment]
yup i understand completly. but yeah u've already made a fantastic job with this stub

by any change could u redirect me to someone who's selling crypting service?

**Comment by bytecode77** [comment]
Since I have no need to buy a crypter, I don't know which paid product is the best. Only thing I know is that it's work to maintain a crypter FUD which is the reason that free ones, like mine, are not FUD - regardless of overall quality of the project.

But if you just need something to use on your binaries, you'll find one ;) Have fun
