### ISSUE TITLE
dependency 

### ISSUE THREAD

**Issue by bashird56** [bytecode77/pe-union#3]
can u share all .net dependency's i m not sure way after installing .net  as instructed pe dos not start i dont know its win7 or something else

**Comment by bytecode77** [comment]
The application targets .NET 4.6, while the compiled stub uses the 4.0 version of the compiler. This is to increase compatibility to any .NET 4.x version.

However, if your binary seems to crash, here are some step to debug it:

1. Use the Builder and generate C# code instead of the executable (This is the code used to generate the binary)
2. Run the code in Visual Studio and see if it crashes
3. If it only crashes sporadically, that could be an indication that obfuscation is not working properly.

If you have a sample C# file that reproduces the crash, please feel free to re-open the issue or send the file via email.

**Comment by bashird56** [comment]
thanks for your reply

**Comment by bashird56** [comment]
i m looking for a good crypter to hide my payload for red teaming
