### ISSUE TITLE
Not fully undetectable

### ISSUE THREAD

**Issue by Salty-Coder** [bytecode77/pe-union#8]
I wanted to test this and noticed that:

Unencryped - 43/70 engines detected it.
Encrypted - 39/70 engines detected it.

There isn't much change...

**Comment by bytecode77** [comment]
PEunion does a good job at binding multiple executables. However, I'm aware that the encryption part lacks behind. In fact, the decrypted file written back to the disk makes this design overhauled. Since my two most recent projects are both 100% fileless, PEunion should also execute decrypted files in memory.

Therefore, a technological overhaul of PEunion is on the agenda for this year. The goal is to compile the output binary as a native assembly with no file drops whatsoever and compile time & runtime obfuscation to be undetectable by both signatures and heuristically. There's a lot room for improvement everywhere.

I cannot make any promises for when the next major version will be released, but I just wanted to share some of the plans.

**Comment by Odsodium** [comment]
Actually I think this program by itself is not very good for bypassing common avs, however if you pair it with other free crypters on github it can bypass windows defender with no problem. It is quite good as a binder because you can add exclusions for windows defender using a simple PowerShell script. Here are my results after using this with another crypter on github
![image](https://user-images.githubusercontent.com/74337450/125381782-9f550880-e3e8-11eb-941d-20e2fe19579d.png)

**Comment by buivannhat** [comment]
> > trước khi có bản mới, tôi có thể sửa lỗi này bằng cách nào đó. làm ơn
> 
> Nếu bạn đang tìm cách tự khắc phục sự cố này, bạn có thể thử thay thế `CompileAssemblyFromSource`bằng `CompileAssemblyFromFile`trong mã và xem liệu điều này có giải quyết được sự cố hay không. Nếu không, bạn có thể thử nghiên cứu & sửa lỗi;) Công việc kinh doanh hàng ngày của một lập trình viên ... Chúc may mắn! Tôi sẽ đăng tất cả các vấn đề GitHub hiện đang mở bất cứ khi nào có phiên bản mới.

tôi có thể liên lạc với bạn bằng cách nào. tôi cần trợ giúp , làm ơn

**Comment by buivannhat** [comment]
![image](https://user-images.githubusercontent.com/88276446/131200374-ce2fe5a3-b90e-41e2-bdb5-f13f34ffbe20.png)
help me

**Comment by bytecode77** [comment]
`CompileAssemblyFromFile` accepts a **path** to a file, not a **string** containing C# code. As I have mentioned in the main page, PEunion is provided "as-is" until the next major release is available to everybody. In the meantime, I would suggest you to get familiar with CodeDom. I don't have the time to support you with basic debugging and problem solving. So, I would kindly ask you to put in the effort, if you want to fix a bug in the code. I will continue working on PEunion 4.0.

**Comment by buivannhat** [comment]
Tôi hi vọng bản PEunion 4.0 được ra mắt sớm nhất

**Comment by bytecode77** [comment]
# PEunion 4.0.0

The new version of PEunion has been released. All currently open GitHub issues were addressed in the release. Additionally, the new version is a complete rewrite and addresses known issues by fundamental architectural changes.

For more info, please read the main page of PEunion to get an overview over features & functionality.

*This message was posted in all currently open GitHub issues.*

It there are any issues in the new version, I would like to ask everybody to create a new GitHub issue instead of posting here. This way, I will have a better overview over issues in PEunion 3.x vs 4.0
