### ISSUE TITLE
Issues compiling.

### ISSUE THREAD

**Issue by the-atf** [bytecode77/pe-union#9]
When I try to compile the file I get the error shown here,

CS2001: Source file 'dir*\AppData\Local\Temp\tmp2D4.tmp' could not be found

*my windows directory does have a space in it, maybe that is to blame?

Any help is appreciated.
Thank you.

**Comment by bytecode77** [comment]
I looked at the code in `Builder.cs`, but I don't see any partiular unquoted commands. Could you check by downloading the code and debug it to see where the exception is thrown? Another thing that's worth trying is to deactivate your AV when you build the file. AV software is always a drag when working with these kinds of software.

**Comment by bytecode77** [comment]
# PEunion 4.0.0

The new version of PEunion has been released. All currently open GitHub issues were addressed in the release. Additionally, the new version is a complete rewrite and addresses known issues by fundamental architectural changes.

For more info, please read the main page of PEunion to get an overview over features & functionality.

*This message was posted in all currently open GitHub issues.*

It there are any issues in the new version, I would like to ask everybody to create a new GitHub issue instead of posting here. This way, I will have a better overview over issues in PEunion 3.x vs 4.0
